### ISSUE TITLE
Have you read the second book——practitioner Bundle

### ISSUE THREAD

**Issue by gittigxuy** [jercas/DeepLearningForComputerVisionWithPython_LearningCode#1]
could you please release the second book's code?this repo is very helpful to me,Thank you

**Comment by jercas** [comment]
I am still reading the second book, and i will release the practitioner bundle code as soon as i finished each chapter. And thanks for your star and follow. It's would be a huge motivation for me to learn. If you have any question want to communicate with me abound deep learning or computer vision, i am looking forward to hearing from you. (In the end, please forgive my english grammer.)

**Comment by gittigxuy** [comment]
I would appreciate to you if you could send the second and the third bundle pdf to me，my email is mdjxy63@gmail.com，Thank you

**Comment by programmingblog** [comment]
I would appreciate to you if you could send the second and the third bundle code to me，my email is hoanganhtuanctes@gmail.com，Thank you!

**Comment by jrosebr1** [comment]
Hey @gittigxuy , @jercas , and @programmingblog -- Adrian here from PyImageSearch.com. I'll be honest with you, I'm not too happy to find this repo and this discussion. I'll be submitting a takedown notice to GitHub.
